BUILD
doc/langdef.md

Add 'in' operator to the core CEL syntax.

 Add 'in' operator to the core CEL syntax.

---

doc/langdef.md

using EBNF for the grammar syntax, and add additional clarification.

Update grammar description to what's current in the implementations,

---

proto/v1/BUILD

with Copybara import from Github.

Fix BUILD file comment syntax issue that was causing a problem

---

doc/langdef.md

Big overhaul of language definition to
- incorporate clarifications from semantics effort for which we have language council consensus;
- rearrange presentation for better flow;
- expand discussions in several places;
- convert to Github-flavored markdown.

Semantics-0.1.0.A

---

doc/langdef.md

Add a note on simulating traditional left-to-right short-circuiting AND and OR with the conditional operator.

Note on simulating traditional logical operators.

---

doc/langdef.md

cl-211103961, one line change.

export changes to external

---

testdata/BUILD.bazel

Migrate testdata into cel-spec #27

add C++ proto library

---

tests/simple/testdata/basic.textproto

* Add zero-ish value representation tests for int/uint/double/string/bool/null/bytes/list/map
* Add nonzero-ish value representation tests for int/uint/double/string/bool/bytes/list/map

test: Add basic tests for zero/empty and nonzero/empty

---

tests/simple/testdata/broken.textproto
tests/simple/testdata/fields.textproto

tests for field selection, it includes map fields selection and namespace resolution. Test related to protobuf does not be included.

conformance: field selection

---

tests/simple/testdata/comparisons.textproto

Add 10 bound variable comparators tests.
Combining comparison operators (_==_, _!=_, _<_, _>_, _<=_, _>=_) with data types, sides (left, right) and expected results (true, false, no_such_overload.

conformance: bound variable comparator tests

---

tests/simple/testdata/broken.textproto
tests/simple/testdata/fp_math.textproto

Add tests for floating point math.

conformance: fp math

---

tests/simple/simple.go
tests/simple/simple_test.go
tools/celrpc/celrpc.go

Minor updates to the go code for style and to address lint warnings.

Lint fixes to the CEL Spec Go code.

---

tests/simple/testdata/lists.textproto
tests/simple/testdata/logic.textproto
tests/simple/testdata/string.textproto
tests/simple/testdata/timestamps.textproto

Added conformance tests for lists, logical not, string concatenation, and timestamps.

Added additional conformance tests

---

doc/langdef.md
proto/test/v1/simple.proto
tests/simple/testdata/broken.textproto
tools/proto_utils_lib_test.cc

Will eliminate some warnings in future imports.

Formatting cleanups.

---

tests/simple/simple_test.go

Add flag for testing that allows ability to skip specific conformance tests

Add skip_test flag

---

doc/langdef.md

Various formatting and context fixes.

Langdef fixes

---

tests/envcheck/README.md

Fix a typo in the test rule example.

Update the envcheck bazel instructions.

---

tests/simple/testdata/README.md
tests/simple/testdata/basic.textproto
tests/simple/testdata/namespace.textproto

Remove reference to the old "broken" file too.

Split out namespace conformance tests.

---

tests/simple/testdata/README.md
tests/simple/testdata/basic.textproto
tests/simple/testdata/comparisons.textproto
tests/simple/testdata/conversions.textproto
tests/simple/testdata/fields.textproto
tests/simple/testdata/integer_math.textproto
tests/simple/testdata/lists.textproto
tests/simple/testdata/logic.textproto
tests/simple/testdata/string.textproto
tests/simple/testdata/timestamps.textproto

Clarifies many unspecified corners of the language, especially rounding in numeric conversions.

Conformance tests for remaining standard functions.

---

tests/simple/testdata/macros.textproto

Tests for exists_one(), map(), and filter() macros.

Conformance tests for additional macros.

---

tests/simple/simple.go
tests/simple/simple_test.go

Back-porting original contribution from Kuat.

Flag to skip check phase on all conformance tests.

---

doc/langdef.md

Time and space costs for expressions.

---

proto/test/v1/proto2/test_all_types.proto
proto/test/v1/proto3/test_all_types.proto

Make sure proto option values are appropriately set for the cel-sepc protos.

Update the proto options for cel-spec protos

---

tests/simple/testdata/comparisons.textproto
tests/simple/testdata/proto2.textproto

Add conformance tests for the null comparison related changes proposed and approved in https://github.com/google/cel-spec/wiki/proposal-210

Heterogeneous null conformance tests

---

doc/langdef.md

Spelling fixes at lines 778 and 796. Minor grammar fixes at lines 513 and 587.

Minor typos and grammar fixes

---

tests/simple/testdata/comparisons.textproto
tests/simple/testdata/fields.textproto
tests/simple/testdata/lists.textproto
tests/simple/testdata/macros.textproto
tests/simple/testdata/proto2.textproto

Update and add tests to reflect changes related to heterogeneous equality.

Numeric in/equality tests across numeric types

---

doc/langdef.md

This change documents the behaviors for equality and ordering:
- Distinguish between homogeneous equality at type-check and heterogeneous equality at runtime
- Ensure `NaN` handling is consistent with IEEE 754
- Document protobuf equality semantics
- Document cross-type numeric equality and ordering.
Closes #54

CEL Spec update to document heterogeneous equality, NaN, and ordering

---

doc/langdef.md

Minor updates for clarity and fixes to the table of content relative links.

Updated the langdef index and clarified some of the spec language

---

proto/dev/cel/expr/conformance/BUILD.bazel
proto/dev/cel/expr/conformance/conformance_service.proto

From https://github.com/googleapis/googleapis/blob/master/google/api/expr/conformance/v1alpha1/conformance_service.proto
but without the dependency on google/api/client.proto

Add ConformanceService definition

---

proto/dev/cel/expr/conformance/BUILD.bazel
proto/dev/cel/expr/conformance/conformance_service.proto
proto/dev/cel/expr/conformance/envcheck.proto
proto/dev/cel/expr/conformance/simple.proto

Placing them so the package and folders match.

Add test protos to dev.cel.expr.conformance

---

tests/simple/testdata/string_ext.textproto

Ported from the cel-go unit tests

Add string ext conformance tests

---

proto/dev/cel/expr/conformance/simple.proto

Needed for locale specific formating testing.

Add locale for string format tests

---

README.md
doc/langdef.md

Minor corrections to the CEL spec and function docs.
Updates information on AST serializability in reference to #385

Minor corrections to the CEL spec and function docs

---

doc/langdef.md

Update the getDate and getDayOfMonth examples

---

proto/cel/expr/checked.proto

Updating the advice for documenting CEL variables and functions.

Add a doc field on Function and update content advice

---

.bazelversion
MODULE.bazel
cloudbuild.yaml

Upgrade the googleapis repo deps, remove switched_rules
