WORKSPACE, proto/checked/README, proto/checked/v1/BUILD, proto/checked/v1/LICENSE, proto/checked/v1/checked.proto, proto/v1/BUILD, proto/v1/LICENSE, proto/v1/syntax.proto, proto/v1/value.proto
First commit is the main Copybara export.
Second commit is a minor fixup of a Copybara problem that was generating invalid Bazel BUILD files.
=>  Add .proto files of the binary representations used in CEL.

CODE_OF_CONDUCT.md
The reference to the Angular project had been erroneously left in when the CoC was adapted from Angular's CoC.
=> Remove reference to Angular project.

doc/langdef.md
Revert the changes back to the one that override them(from #16 to #12).
=> Revert langdef.md changes

doc/langdef.md
Similar to octal behavior, these represent codepoints for strings and octets for byte literals.
[cel-go](https://github.com/google/cel-go/blob/master/parser/unescape.go#L150) implements this
=> Add `\xFF`-style hex escapes to the spec

tests/simple/testdata/basic.textproto, tests/simple/testdata/broken.textproto, tests/simple/testdata/comparisons.textproto
Adding basic equality and lookup tests:
- _==_ tests for int/uint/double/string/null/bool/byte/list/map.
- Basic lookup tests.
- `broken.textproto` for the issues reported (google/cel-go#154 and google/cel-go#155)
=> conformance-tests: basic "==" and lookup tests

tests/simple/testdata/basic.textproto, tests/simple/testdata/broken.textproto, tests/simple/testdata/comparisons.textproto
Add tests for the `_!=_` operand on `int/uint/float/string/bool/null/bytes/list/map`.
Bonus track: Fixing some of the original test names' to utilize the correct naming for floating point numbers.
=> conformance: Add tests for _!=_

tests/simple/testdata/comparisons.textproto
Add literal comparison tests for `_<_`, `_>_`, `_<=_` and `_>=_`, for `int64`, `uint64`, `float`, `bool`, `bytes`, and the unsupported `null`, `list` and `map`s.
This PR is the last of the Cartesian product batch.
Feel free to suggest addition/changes/removals. Thanks!
=> conformance: Add literal comparison tests for <, >, <=, >=

tests/simple/testdata/broken.textproto, tests/simple/testdata/comparisons.textproto, tests/simple/testdata/fields.textproto
Move fixed tests out of `broken.textproto` and into their rightful homes.
=> Move fixed tests into their appropriate locations.

tests/simple/testdata/broken.textproto, tests/simple/testdata/fields.textproto
The `ident_with_longest_prefix_eval` broken test is fixed in CEL-Go at HEAD, moved to indicates this should now be part of the working conformance suite.
=> Update the CEL Spec conformance tests to include fixes from CEL-Go

tests/simple/testdata/broken.textproto, tests/simple/testdata/comparisons.textproto, tests/simple/testdata/macros.textproto
Add conformance tests for the `in` operator, the `exists` macro, and an additional map equality test.
Also, note a broken case on the current cel-go implementation for a very unlikely map configuration which is permissible given the spec.
=> In and equality tests

doc/langdef.md, tests/simple/testdata/basic.textproto, tests/simple/testdata/comparisons.textproto
Remove unicode escapes in byte literals in conformance tests.
=> Byte and string literals match Google SQL.

doc/langdef.md
=> Typo in langdef.md

README.md
Add link to CEL conformance dashboard and instructions on how to create additional dashboards.
=> Add dashboard documentation to cel-spec

tests/simple/testdata/macros.textproto
The all() macro should join the elements by logical AND, and the
exists() macro should join the elements by logical OR.
=> Conformance tests for macro equivalence to logic.

proto/test/v1/proto2/BUILD.bazel, proto/test/v1/proto2/test_all_types.proto, proto/test/v1/proto3/BUILD.bazel, proto/test/v1/proto3/test_all_types.proto, tests/simple/BUILD.bazel, tests/simple/simple_test.go, tests/simple/testdata/proto2.textproto, tests/simple/testdata/proto3.textproto
Allows conformance tests to bind variables to protobuf message values, and to expect protobuf messages as evaluation results.  Both proto2 and proto3 are supported.
Adds initial conformance tests for proto2 and proto3 - just enough to demonstrate that the plumbing works.  More conformance tests will be added in future PRs.
The C++ filter written to parse expanded "Any" messages in textproto is no longer required and will be removed in a future PR.
=> Proto support for conformance tests

tests/simple/BUILD.bazel, tests/simple/simple.go, tests/simple/simple_test.go, tests/simple/testdata/fp_math.textproto
Also tweak conformance test expected results for negative zero, which is now surfaced as significant.
=> Handle nested Any comparisons in simple tests.

doc/langdef.md, tests/simple/testdata/comparisons.textproto
=> No unicode normalization: spec and tests.

doc/langdef.md, tests/simple/testdata/comparisons.textproto
Updates spec and adds conformance tests.
Closes #127
=> Clarify homogeneous equality on lists and maps

doc/langdef.md
Also clarify the list of reserved words by aligning EBNF with the text of the specificaiton.
=> Address issue #126 (syntax of signs)

doc/langdef.md
These were never implemented and have no purpose.
Closes #123
=> Remove unused list and map type conversions.

GOVERNANCE.md, MAINTAINERS.md
I have written up the CEL governance process to mirror and formalize the first real case we've had of a feature request which merited it: https://github.com/google/cel-go/issues/340
Closes #133
=> Document the CEL governance process

doc/langdef.md, tests/simple/testdata/basic.textproto, tests/simple/testdata/comparisons.textproto
This change adds more basic tests for string and integer literals. It also updates the lexis to include the 8 hexadecimal digit variant of Unicode code point escape sequences.
=> Add basic tests and update lexis

tests/simple/simple.go, tests/simple/simple_test.go
Also add a flag to skip tests which skip type checking, so checked-only
evaluators don't have to maintain their own list of tests to skip.
=> Conformance: eval both checked and parsed ASTs.

doc/langdef.md, tests/simple/testdata/enums.textproto
Remove note about google.protobuf.EnumValue as a wrapper type.
=> Conformance tests for enums and no wrapper.

tests/simple/testdata/dynamic.textproto
This reverts commit 29370528731ae703183537e7072b5ad6c8c0bf96.
=> Revert "Fix test by removing invalid double nesting of value"

doc/intro.md
The type should just be `list` and not `list(string)` which we moved away from quite some time ago.
=> Remove bad type specification in example

tests/simple/testdata/comparisons.textproto
In the spec there is no overload that could match null < x, so implementations should be allowed to fail type checking for this.
Cel-go doesn't, because it considers well-known types nullable, so e.g the overload timestamp < timestamp matches this at type-checking (but not at run-time).
=> Disable typecheck for null < x conformance test

doc/langdef.md
These are present in the conformance tests.
=> Add string conversion for timestamp and duration to spec

tests/simple/testdata/timestamps.textproto
Add leading zeros to numeric timezone arguments. It's possible that some implementations may be more lenient in the timezones accepted, but the spec and tests should declare support for the more conservative format.
Closes #194
=> Ensure that numeric timezones in tests are spec-consistent

doc/langdef.md
Update the spec to indicate the duration string format supported by the core CEL implementations:
Update the spec to indicate the format supported by C++, Java, and Go:
https://github.com/abseil/abseil-cpp/blob/master/absl/time/time.h#L577
https://github.com/ThreeTen/threeten-extra/blob/master/src/main/java/org/threeten/extra/AmountFormats.java#L327
https://pkg.go.dev/time#ParseDuration
Closes #185
=> Document the duration string format supported by core implementations

doc/langdef.md, tests/simple/testdata/conversions.textproto, tests/simple/testdata/timestamps.textproto
Additional documentation and tests for timestamp and duration overflow behavior.
There is also a note about why `double -> int` and `double -> uint` overflow at
`minInt`, `maxInt`, and `maxUint` since some runtimes may support a conversion
from double to int depending on compiler options.
=> Additional tests for overflow and documentation of overflow conditions

doc/langdef.md
All lexer/parsers have been updated support trailing commas in aggregate literal types. Updating the spec to reflect the implementation behavior.
Closes #155
=> Update the spec to support trailing commas in list, map, and struct literals

tests/simple/testdata/timestamps.textproto
Closes #175
Bug also filed for https://github.com/google/cel-go/issues/453 to address spec conformance.
=> Update the get_milliseconds test to match the spec

tests/simple/testdata/comparisons.textproto
This generally follows the default behavior of the C++
protobuf MessageDifferencer (compare fieldwise, unpacking Any values where
possible).
=> Add conformance tests for message equality for CEL.

doc/langdef.md
The BNF definition of `ESCAPE` provided does not match the text.
> Escape sequences are a backslash (`\ `) followed by one of the following:
> 
> *   A punctuation mark representing itself:
>     *   `\ `: backslash
>     *   `?`: question mark
>     *   `"`: double quote
>     *   `'`: single quote
>     *   `` ` ``: backtick
> *   A code for whitespace:
>     *   `a`: bell
>     *   `b`: backspace
>     *   `f`: form feed
>     *   `n`: line feed
>     *   `r`: carriage return
>     *   `t`: horizontal tab
>     *   `v`: vertical tab
The BNF is missing `a`, `v`, `?`, `` ` ``
```
ESCAPE         ::= \ [bfnrt"'\]
| \ x HEXDIGIT HEXDIGIT
| \ u HEXDIGIT HEXDIGIT HEXDIGIT HEXDIGIT
| \ U HEXDIGIT HEXDIGIT HEXDIGIT HEXDIGIT HEXDIGIT HEXDIGIT HEXDIGIT HEXDIGIT
| \ [0-3] [0-7] [0-7]
```
=> Fix spec `ESCAPE` definition mismatch

tests/simple/simple_test.go, tools/celrpc/BUILD.bazel, tools/celrpc/celrpc.go, tools/celrpc/celrpc_test.go, tools/celrpc/testpipeimpl/main/BUILD.bazel, tools/celrpc/testpipeimpl/main/main.go
JSON/Proto serialization has some limitations and subtly differnet behavior between environments. Base64 encoding the wire format of the protobuf messages should lead to fewer false positives.
=> Add support for piping conformance tests using base64 encoded messages.

tests/simple/testdata/string.textproto
This will check that CEL's standard functions for strings is able to deal with unicode literals past the BMP.
=> Add test cases for String standard functions with Unicode in Supplemental Multilingual Plane

WORKSPACE, proto/test/v1/BUILD.bazel, tests/envcheck/BUILD.bazel, tests/simple/BUILD.bazel, tools/celrpc/BUILD.bazel, tools/celrpc/testpipeimpl/main/BUILD.bazel
This change shifts from depending on all of googleapis to just the ones under api/ and rpc/
=> Updates to the Bazel WORKSPACE to support granular go-genproto targets

README.md
Travis CI isn't used any longer for CI, resulting in a broken image link in GitHub.
=> README.md: Remove Travis CI link.

WORKSPACE, proto/dev/cel/expr/conformance/BUILD.bazel, proto/dev/cel/expr/conformance/conformance_service.proto
Update the go package for conformance protos.
This change also updates the associated WORKSPACE and BUILD.bazel targets
=> Update the conformance service build targets

proto/buf.yaml
To control which files get synced to https://buf.build/cel/spec.
=> Add a buf.yaml for Buf CLI compatibility

proto/buf.yaml, proto/cel/expr/BUILD.bazel, proto/cel/expr/checked.proto, proto/cel/expr/conformance/BUILD.bazel, proto/cel/expr/conformance/conformance_service.proto, proto/cel/expr/conformance/envcheck.proto, proto/cel/expr/conformance/proto2/BUILD.bazel, proto/cel/expr/conformance/proto2/test_all_types.proto, proto/cel/expr/conformance/proto3/BUILD.bazel, proto/cel/expr/conformance/proto3/test_all_types.proto, proto/cel/expr/conformance/simple.proto, proto/cel/expr/eval.proto, proto/cel/expr/explain.proto, proto/cel/expr/syntax.proto, proto/cel/expr/value.proto
To match the following:
- proto: cel.expr.* / "cel/expr/*"
- c++: cel::expr::* / "cel/expr/*"
- go: cel.dev/expr
- java: dev.cel.expr (unchanged)
The tld is typically not included in proto/c++, and was in the wrong spot for the go package.
This leaves the existing protos inplace, to allow for a transition to the new packages.
=> Update the proto, go, and c++ packages

README.md
The test grid link in the README.md refers to a dashboard
which hasn't been updated since 2020. 
Conformance can better be determined from running the conformance
test target in the [cel-go](https://github.com/google/cel-go),  [cel-cpp](https://github.com/google/cel-cpp), or [cel-java](https://github.com/google/cel-java) repos directly.
Closes #309
=> Update TestGrid link in README.md

tests/simple/simple_test.go, tools/celrpc/BUILD.bazel, tools/celrpc/celrpc.go, tools/celrpc/celrpc_test.go, tools/celrpc/testpipeimpl/main/BUILD.bazel, tools/celrpc/testpipeimpl/main/main.go
- Add  a simple ping protocol to pipe clients conformance service
- Pinging the subprocess tends to be a bit more reliable than checking health via other means
- Default pipe to use base64 encoding instead of JSON
=> Add support for a ping command to pipe clients.

doc/langdef.md
None of the stacks (cel-go, cel-cpp, cel-java) currently support strongly typed enum, leading to confusion. We may revisit this when we add concrete support for this in any of the stacks in the future.
=> Remove strongly typed enum support from the specification

doc/langdef.md
The specification is missing the 3 arg map function, which allows for condition, `p`, which is evaluated before the transformation. Updating the language spec docs to include this existing function.
\- adamsinclair@
=> [docs] Update langdef.md to include 3-arg map fn

proto/cel/expr/syntax.proto
Add a notion of Extensions to the pb representation for CEL ASTs.
These allow for tagging what things the parser or type checker expect of the runtime and allow for graceful degredation if an implementation doesn't support a given extension.
=> Add definition for extensions to Syntax proto

tests/simple/testdata/optionals.textproto
These are direct transcriptions of the evaluation tests using by CEL Go.
=> Add initial `optional_type` conformance tests

doc/langdef.md, tests/simple/testdata/macros.textproto
These macros are documented as explicitly not applying to map values, but it seems like this documentation is out-of-date.
Expressions in the playground:
- [`.map()`](https://playcel.undistro.io/?content=H4sIAAAAAAAAA6tWSkksSVSyUiouKcrMS%2FdNLLCKyVNQSLRSqADRSVYKlTF5MXlKOkqpFQVFqcXFmfl5yKr1chMLNLJ1FLI1lWoBx1LL3EwAAAA%3D)
- [`.filter()`](https://playcel.undistro.io/?content=H4sIAAAAAAAAA6tWSkksSVSyUiouKcrMS%2FdNLLCKyVNQSLRSqADRSVYKlTF5MXlKOkqpFQVFqcXFmfl5yKr10jJzSlKLNLJ1FLIVbG0V1BPVNZVqAbO9entWAAAA)
=> doc/langdef: update documentation for .map() and .filter()

tests/simple/testdata/macros.textproto, tests/simple/testdata/math_ext.textproto
Map key iteration order is not guaranteed, so the test exercising this behavior
needed to be modified to a map with a single key to prevent flakiness
=> Fix map iteration expectations and trim ending whitespace

tests/simple/testdata/optionals.textproto
Ensure that accessing a null valued key is covered within optional tests
Within cel-go there was a bug where the implementation did not match the spec:
https://github.com/google/cel-go/issues/937
=> Additional conformance tests for accessing a null valued field

tests/simple/testdata/enums.textproto
C++ protobuf rejects unknown enum values in proto2, as proto2 enums are supposed to be closed. I believe Go/Java protobuf incorrectly accept these at the moment. This only affects textproto parsing. This PR removes these incompatible tests.
=> Remove unknown proto2 enum values

tests/simple/testdata/math_ext.textproto
Various `math_ext` conformance tests regarding bitwise right shift of negative numbers were incorrect. Per the spec, right shifting negative numbers *does not* perform sign extension. Instead we treat `int >> int` the same as `uint >> int`.
=> Fix math_ext conformance tests to be correct

proto/cel/expr/syntax.proto
The comprehensions v2 support iteration over (key, value)
and (index, value) tuples within lists and maps.
=> Introduce iter_var2 in support of comprehensions v2

tests/simple/testdata/optionals.textproto, tests/simple/testdata/proto2.textproto, tests/simple/testdata/proto3.textproto, tests/simple/testdata/wrappers.textproto
Conformance tests for 'null' assignment to a field
Generally, setting a proto field to null within a `CreateStruct` block
should result in the field being unset; however, there are some exceptions:
* Repeated and map fields cannot be unset via `null`
* The `google.protobuf.Any` and `google.protobuf.Value` types 
treat `null` as a concrete JSON `null`
=> Conformance tests for 'null' assignment to a field

doc/langdef.md, tests/simple/testdata/conversions.textproto
The following identity functions are being added: `bool`, `int`, `uint`, `double`, `string`, `bytes`, `timestamp` and `duration`.
These are already fully included in cel-go, mostly present in [cel-cpp](https://github.com/google/cel-cpp/pull/851) and the same are being added in [cel-java](https://github.com/google/cel-java/pull/405)
=> Add identity functions to the standard definitions

tests/simple/testdata/string_ext.textproto
Copied from https://github.com/google/cel-go/blob/master/ext/strings_test.go, except locale overrides and compile-error tests.
=> Add string.format conformance tests

proto/test/v1/proto2/test_all_types.proto, proto/test/v1/proto3/test_all_types.proto
This will allow the duplicate test_all_types proto to be removed from here: https://github.com/google/cel-java/blob/main/common/src/main/resources/testdata/proto2/test_all_types.proto
=> Add nested groups to proto2 and optional fields to proto3 test protos

BUILD.bazel
cel-spec identifies itself as `cel.dev/expr`. This means if I'm using bazel downstream, my targets end up failing because it can't find this.
This simple rule fixes that problem.
=> Add a default expr target

doc/langdef.md
Provide more useful documentation for the CEL types, functions, and macros
=> Update to the standard function docs

BUILD.bazel, WORKSPACE, go.mod, go.sum, proto/cel/expr/BUILD.bazel, proto/cel/expr/conformance/BUILD.bazel, tests/go.mod, tests/go.sum
The import path for a local google.rpc.Status rule may potentially be causing
problems for upstream users.
#390
=> Remove local copy of google.rpc.Status proto

tests/simple/simple_test.go
Doing the flag.Parse in init() erases the Go Test's builtin options such as -test.v. The right place to do that is TestMain and we even do that already. Remove the one in the init() function.
=== Before the change ===
Usage of ./simple.test:
-check_server string
path to command for check server
-checked_only
skip tests which skip type checking
-eval_server string
path to command for eval server
-parse_server string
path to command for parse server
-pipe
Use pipes instead of gRPC
-pipe_base64
Use base64 encoded wire format proto in pipes (if disabled, use JSON). (default true)
-pipe_pings
Enable pinging pipe client to subprocess status.
-server string
path to binary for server when no phase-specific server defined
-skip_check
force skipping the check phase
-skip_test value
name(s) of tests …
=> test, simple: Don't parse the flag in init()

doc/langdef.md
=> Fix spelling in code sample

doc/langdef.md
This is a minor tweak, but the current rendering of the explanation looks like it's either three or five characters, not the four cited, causing some potential confusion.
=> Make meaning of '''x''x''' more readable.

tests/simple/testdata/block_ext.textproto
This will ensure that conformance processes doing type-checking find the variables correctly.
=> Set the type_env field on all block tests with bindings

proto/test/v1/BUILD.bazel, proto/test/v1/simple.proto
For migration purposes reinstate the `proto/test/v1/simple.proto` version
of the conformance test proto.
=> Temporarily restore simple.proto to its former location 

doc/langdef.md
`7.` is not in fact a valid double literal per the grammar or the `cel-go` implementation. But `.700e1` is, and shows off some other aspects of flexibility in the grammar.
=> Correct double literal example

proto/cel/expr/conformance/test/simple.proto, proto/test/v1/simple.proto
Add matcher for checking type deductions in conformance tests.
This will be used to validate the checker implementations deduce the same overall type separately from having the same behavior at runtime.
=> Add typed result matches to SimpleTest definition

tests/simple/testdata/type_deduction.textproto
This adds a few minimal tests for type deduction for conformance testing. Additional tests will be added after validating that the Go, C++, and Java test runners support this style of test.
=> Add basic tests for type deductions.

tests/simple/testdata/type_deduction.textproto
Addional tests covering more complicated type inference cases.
- wrapper handling when choosing candidate for type parameter
- legacy nullabilty
- specialization of parameterized types e.g prefering list(list(T)) over list(T)
=> Add additional type check tests

doc/langdef.md
=> clarify error behavior for e.exists(x, p)

doc/langdef.md, tests/simple/testdata/comparisons.textproto
=> clarify Unicode handling

tests/simple/testdata/string_ext.textproto
Fix scientific formatting to be correct. It appears Go is wrong and inserts non breaking spaces before and after the superscriptingExponent. ICU has the correct behavior. Go needs to be fixed itself.
Also fix double formatting such that `%s` for maps and list formats doubles as if by `%s` as well.
=> Fix strings.format tests

doc/extensions/strings.md, tests/simple/testdata/string_ext.textproto
Upon further investigation, it turns out `string.format` as implemented today is very inconsistent, not intuitive, and sometimes does wonky things like accept strings but only if they are one of the special strings that `double` accepts for infinity and nan. Sometimes it localizes and sometimes it does not. Localization also requires taking on large dependencies such as `ICU4C`, `ICU4J`, and `golang.org/x/text`.
To resolve, we should remove localization entirely and standardize what each conversion is supposed to do for each type. This PR includes a draft of standardization and updates the tests data to reflect it.
=> Fix and document string.format

doc/langdef.md
=> update grammar and tests to differentiate reserved tokens

proto/cel/expr/BUILD.bazel
This allows using the protos in Python.
Note, in reference to two old, alternative PRs ([PR1](https://github.com/google/cel-spec/pull/318), [PR2](https://github.com/google/cel-spec/pull/325)): To the best of my knowledge, there are (or there used to be) three implementations of `py_proto_library` to choose from, and they don't mix well. The Protobuf team has taken ownership of `py_proto_library` and the implementation from the Protobuf repository is the one to use now.
- The `py_proto_library` from `rules_python` [has been removed](https://github.com/bazel-contrib/rules_python/pull/1933) in favor of the one from Protobuf.
- The `py_proto_library` from gRPC is also deprecated. [gRPC is migrating](https://github.com/grpc/grpc/pull/37866) to the one from Protobuf.
=> Add py_proto_library targets

tests/simple/testdata/string_ext.textproto
=> Revert "Remove Unicode space handling from <string>.trim()"

tests/simple/testdata/timestamps.textproto
timestamp and duration are referred to by the corresponding protobuf types `google.protobuf.(Timestamp|Duration)`
includes misc automated formatting fixes
=> Add tests for type identifiers for time types

proto/cel/expr/BUILD.bazel, proto/cel/expr/conformance/test/suite.proto, proto/cel/expr/eval.proto
Updated testsuite result_kind to use nested ErrorSet and remove dependency from cel.expr.ErrorSet since in Java this causes classpath conflict when adding com.google.api.grpc:proto-google-common-protos.
=> Updated testsuite result_kind to use nested ErrorSet
